name: fluttertry5
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.30
#  flutter_polyline_points: ^0.2.1
  geolocator: ^5.3.1
#  cupertino_icons: ^0.1.2
  http: ^0.12.0
  font_awesome_flutter: ^8.8.1
  pie_chart: ^4.0.1
  charts_flutter: ^0.9.0
  map_launcher: ^0.12.2
  location: ^3.0.2
  flutter_swiper: ^1.1.6
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
  geocoding: ^1.0.5
  geocoder: ^0.2.1
#  linkable: ^1.0.4
  url_launcher: ^5.4.11
  google_fonts: ^1.1.0
  flutter_svg: ^0.17.3
#  geolocator:
#  cell_calendar: ^0.1.2
#  flutter_screenutil: ^3.2.0
#  table_calendar: ^2.3.0
#  flutter_localizations:
#    sdk: flutter
#  flutter_rounded_date_picker: 1.0.5
  flutter_calendar_carousel: ^1.5.1
  path_provider: ^1.6.24
#  date_format: ^1.0.5
  intl: ^0.16.1
  marquee: ^1.5.2
  fl_chart: ^0.2.0
#  animated_text_kit: ^2.5.0
  #  link_text: ^0.1.0
#  flutter_linkify: ^3.1.3

#  geolocator: ^6.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

#    uses-material-design: true
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
      - Images/logo2.png
      - Images/sun.png
      - Images/barrier.png
      - Images/snake1.png
      - Images/guide.png
      - Images/group.png
      - Images/luggage.png
      - Images/logo圓形.png
      - Images/glasses.jfif
      - Images/umbrella.jfif
      - Images/green.jfif
      - Images/chain.jfif
      - Images/flower.jfif
      - Images/step.jfif
      - Images/noice.png
      - Images/calmdown1.png
      - Images/takeoff.png
      - Images/bandage1.png
      - Images/heart.png
      - Images/ambulance.png
      - Images/injection.png
      - Images/try.jpg
      - Images/menu.png
      - Images/remove.png
      - Images/send.png
      - Images/pin11.png
      - Images/remove1.png
      - Images/sun3.png
      - Images/road-block.png
      - Images/snakelogo.png
      - Images/calendar.png
      - Images/monster.jpg
      - Images/school.jpg
      - Images/icon-A.png
      - Images/icon-B.png
      - Images/icon-C.png
      - Images/icon-D.png
      - Images/tai.jpg
      - Images/draw.jpg
      - Images/2.jpg
      - Images/sure1.jpg
      - Images/sure2.jpg
      - Images/sure3.jpg
      - Images/sure4.jpg
      - Images/sure5.jpg
      - Images/sure6.jpg
      - Images/sure7.jpg
      - Images/sure8.jpg
      - Images/tiger.jpg
      - Images/tiger1.jpg
      - Images/smartphone.png
      - Images/homepage.png
      - Images/activity1.jpg
      - Images/activity2.jpg
      - Images/activity3.jpg
      - Images/one.jpg
      - Images/small_logo.png
      - Images/two.jpg
      - Images/three.jpg
      - Images/four.jpg
      - Images/five.jpg
      - Images/six.jpg
      - Images/seven.gif
      - Images/eight.jpg
      - Images/map.png
      - Images/map2.png
      - Images/map3.jpg
      - Images/car.png
      - Images/traffic.png
      - Images/bus.png
      - Images/camera.png
      - Images/movie.png
      - Images/up.jpg
      - Images/TXG.png
      - Images/CWH.png
      - Images/NTO.png
      - Images/school.jpg
      - Images/monster.jpg
      - Images/chickenstory.jpg
      - Images/qinjingsky.jpg
      - Images/rainbowbridge.jpg
      - Images/naturalhistory.jpg
      - Images/midtai.jpg
      - Images/wangartmuseum.jpg
      - Images/teamuseum.jpg
      - Images/dragonwaterfall.jpg
      - Images/ladderbridge.jpg
      - Images/jongxing.jpg
      - Images/midtaitemple.jpg
      - Images/carbonart.jpg
      - Images/japanesecandy.jpg
      - Images/coldspring.jpg
      - Images/dabamboolake.jpg
      - Images/dragonskywalk.jpg
      - Images/longfengwaterfall.jpg
      - Images/wildspring.jpg
      - Images/comphortree.jpg
      - Images/watercloudbridge.png
      - Images/mushroomhome.jpg
      - Images/bigmountainwalk.jpg
      - Images/qinglongwalk.jpg
      - Images/backmountainwalk.jpg
      - Images/tourismmei.jpg
      - Images/frogwalk.jpg
      - Images/likewaterwalk.jpg
      - Images/hanbeewalk.jpg
      - Images/shibumeizu.jpg
      - Images/manshehistoric.jpg
      - Images/lienxingtemple.jpg
      - Images/clouddragonwaterfall.jpg
      - Images/insideforestwalk.jpg
      - Images/wulin.jpg
      - Images/yunfeng.jpg
      - Images/wandareservoir.jpg
      - Images/pulihotspring.png
      - Images/waterwithfire.png
      - Images/guoxinghotspring.jpg
      - Images/taionevilla.jpg
      - Images/wuchangtemple.jpg
      - Images/yichinwine.png
      - Images/fengxiangpark.jpg
      - Images/bridgeonthesky.jpg
      - Images/hideumbrella.jpg
      - Images/hitrock.jpg
      - Images/lingrave.jpg
      - Images/bambooculture.jpg
      - Images/taomivilla.jpg
      - Images/greenhole.jpg
      - Images/jijitrainstation.jpg
      - Images/insidehole.jpg
      - Images/sunmoonlake.jpg
      - Images/ricebridge.jpg
      - Images/paperchurch.jpg
      - Images/nine.jpg
      - Images/glassbridge.jpg
      - Images/yushantea.jpg
      - Images/meizidream.jpg
      - Images/chechentrain.jpg
      - Images/shulibridge.png
      - Images/forgetworry.jpg
      - Images/linoldstreet.jpg
      - Images/shanlinxi.jpg
      - Images/hehuanshan.jpg
      - Images/auowuanda.jpg
      - Images/qinjingfarm.jpg
      - Images/monaludao.jpg
      - Images/hueshunforest.png
      - Images/taiyavacation.jpg
      - Images/twomountain.jpg
      - Images/turtlestrawberry.jpg
      - Images/skytemple.jpg
      - Images/sandart.jpg
      - Images/baodaovillage.jpg
      - Images/workresearch.jpg
      - Images/nineninewalk.jpg
      - Images/ninenineart.jpg
      - Images/bluefield.jpg
      - Images/guobao.jpg
      - Images/snakehole.jpg
      - Images/meifeng.jpg
      - Images/energypig.jpg
      - Images/frontfirstrock.jpg
      - Images/bugmuseum.jpg
      - Images/destination_map_marker.png
      - Images/national-park.png
      - Images/art.png
      - Images/eco.png
      - Images/history.png
      - Images/hot.png
      - Images/jogging.png
      - Images/museum.png
      - Images/pinpin.png
      - Images/fun.png
      - Images/scenery.png
      - Images/temple.png
      - Images/flag.png
      - Images/homepage.png
      - Images/day.png
      - Images/night.png
      - Images/night2.png
      - Images/maplogo.png
      - Images/hospital.png
      - Images/07.jpg
      - Images/08.jpg
      - Images/09.jpg
      - Images/10.jpg
      - Images/11.jpg
      - Images/12.jpg
      - Images/sunmoon.jpg
      - Images/tea.jpg
      - Images/light.jpg
      - Images/puli.jpg
      - Images/year.jpg
      - Images/farming.png
  #   - Images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-Images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-Images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
