name: fluttertry5
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.30
  google_map_polyline:
  geolocator: ^5.3.1
#  cupertino_icons: ^0.1.2
  http: ^0.12.0
  font_awesome_flutter: ^8.8.1
  pie_chart: ^4.0.1
  charts_flutter: ^0.9.0
  location: ^3.0.2
  flutter_swiper: ^1.1.6
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
#  linkable: ^1.0.4
  url_launcher: ^3.0.2
  google_fonts: ^1.1.0
#  link_text: ^0.1.0
#  flutter_linkify: ^3.1.3

#  geolocator: ^6.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

#    uses-material-design: true
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
      - Images/logo2.png
      - Images/sun.png
      - Images/pin.png
      - Images/barrier.png
      - Images/snake1.png
      - Images/guide.png
      - Images/group.png
      - Images/luggage.png
      - Images/logo圓形.png
      - Images/glasses.jfif
      - Images/umbrella.jfif
      - Images/green.jfif
      - Images/chain.jfif
      - Images/flower.jfif
      - Images/step.jfif
      - Images/noice.png
      - Images/calmdown1.png
      - Images/takeoff.png
      - Images/bandage1.png
      - Images/heart.png
      - Images/ambulance.png
      - Images/injection.png
      - Images/try.jpg
      - Images/menu.png
      - Images/remove.png
      - Images/send.png
      - Images/pin11.png
      - Images/remove1.png
      - Images/sun3.png
      - Images/road-block.png
      - Images/snakelogo.png
      - Images/calendar.png
      - Images/monster.jpg
      - Images/school.jpg
      - Images/icon-A.png
      - Images/icon-B.png
      - Images/icon-C.png
      - Images/icon-D.png
      - Images/tai.jpg
      - Images/draw.jpg
      - Images/2.jpg
      - Images/sure1.jpg
      - Images/sure2.jpg
      - Images/sure3.jpg
      - Images/sure4.jpg
      - Images/sure5.jpg
      - Images/sure6.jpg
      - Images/sure7.jpg
      - Images/sure8.jpg
      - Images/tiger.jpg
      - Images/tiger1.jpg
      - Images/smartphone.png
      - Images/homepage.png
      - Images/activity1.jpg
      - Images/activity2.jpg
      - Images/activity3.jpg
      - Images/one.jpg
      - Images/small_logo.png
      - Images/two.jpg
      - Images/three.jpg
      - Images/four.jpg
      - Images/five.jpg
      - Images/six.jpg
      - Images/seven.gif
      - Images/eight.jpg
      - Images/map.png
      - Images/map2.png
      - Images/map3.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
